### ISSUE TITLE
New user

### ISSUE THREAD

**Issue by dbelge** [Lhermine/APSystemsEedomus#1]
Hello,  

I downloaded your script ftome the eedomus store.  And I very apreciate it, thanks a lot!

As i am also interested into obtain the instant production and the instant consumption, i contact you before learning php scripting.  Do you try to get theses values?

It would be valuable for me to create some eedomus rules, like to warm the spa when the production is high...

Thanks in advance,
Dominique

**Comment by Lhermine** [comment]
Hello,

Je viens de mettre à jour le projet gitHub et publier la version sur le store eedomus.
Il faut attendre leur validation

**Comment by dbelge** [comment]
Super!  Un grand merci.  Je teste ça tout à l'heure
